site_name: BIBCAT Publisher
pages:
  - Home: index.md
  - About: about.md
  - Installing: installing.md
  - Hosting: hosting.md
  - Customizing: customizing.md
  - KnowledgeGraph: knowledge-graph.md
  - DigitalRepository: digital-repository.md
theme: readthedocs
